name: Azure Template Validation and Deployment

on:
  workflow_dispatch:  # Manually trigger via GitHub Actions interface

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  validate-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Azure Template
        uses: microsoft/template-validation-action@v0.2.2
        id: validation
        with:
          workingDirectory: ./nckmtemplate  
          validateAzd: true                
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print result
        run: cat ${{ steps.validation.outputs.resultFile }}  # Output the result of the validation step

  deploy-azure:
    runs-on: ubuntu-latest
    needs: validate-template  # This ensures the deployment only happens if validation passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      - name: Deploy Azure Template
        run: |
          az deployment sub create \
            --location ${{ secrets.AZURE_LOCATION }} \
            --template-file ./infra/main.bicep  # Path to your bicep template in the infra folder
            --parameters solutionPrefix=${{ github.event.inputs.solutionPrefix }} otherLocation=${{ github.event.inputs.otherLocation }} baseUrl=${{ github.event.inputs.baseUrl }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
